services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./app/:/usr/share/nginx/html/
