services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/logs/nginx/:/var/log/nginx/
      - ./nginx/logs/letsencrypt:/var/log/letsencrypt/
      - ./app/:/usr/share/nginx/html/:ro
